#! /bin/sh

/bin/mount -a

mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devpts devpts /dev/pts

mdev -s

ifconfig eth0 up
ifconfig eth0 10.71.1.141 netmask 255.255.255.0
ifconfig lo up

ssh-keygen -t rsa1 -f /usr/local/etc/ssh_host_key -N ""
ssh-keygen -t rsa -f /usr/local/etc/ssh_host_rsa_key -N ""
ssh-keygen -t dsa -f /usr/local/etc/ssh_host_dsa_key -N ""
ssh-keygen -t ecdsa -f /usr/local/etc/ssh_host_ecdsa_key -N ""
ssh-keygen -t ed25519 -f /usr/local/etc/ssh_host_ed25519_key -N ""

mkdir /var/empty
mkdir /var/run
mkdir /var/log
touch /var/log/wtmpx

inetd /etc/inetd.conf
klogd
syslogd
/sbin/sshd

hostname mithrandir

export TERM=linux3.0
